### ISSUE TITLE
Do you have any script to plot predicted results over input data for forecasting task? Thanks

### ISSUE THREAD

**Issue by Thanh-Binh** [yuezhihan/ts2vec#11]

**Comment by yuezhihan** [comment]
No. The output file is at `training/DatasetName__RunName_Date_Time/out.pkl`. You can easily load this file with pickle and plot the output.

**Comment by Thanh-Binh** [comment]
Thanks 
What is the format of data?
After loading my data has the length of 5
What does it mean? Number of prediction time steps?

**Comment by yuezhihan** [comment]
> Thanks
> What is the format of data?
> After loading my data has the length of 5
> What does it mean? Number of prediction time steps?

It means the prediction horizon (e.g. 24,48,168,336,720). Check the code in /tasks/forecasting.py for more details.

```
        out_log[pred_len] = {
            'norm': test_pred,
            'raw': test_pred_inv,
            'norm_gt': test_labels,
            'raw_gt': test_labels_inv
        }
```

**Comment by Thanh-Binh** [comment]
I have just look at your source code.
After training I want to use the trained model, e.g. for prediction of time series x0,x1, x2, ... xN by prediction horizon of 10.
How can I call it in the loop?
pseudo-code look like:
for i = 1: N
    currentData = x[i]
    // get prediction data xpred at (i + prediction_horizon)
end

Thanks

**Comment by zifei-yu** [comment]
> _没有提供说明。_
Hello, I have also been studying the ts2vec model recently. When I used the ETTh1 dataset, I encountered a dimension inconsistency problem. Have you ever encountered this problem? I hope to receive your answer. Thank you very much!

**Comment by zifei-yu** [comment]
Hello, do you have the drawing code here? I wonder if you can provide it. Thank you very much!

**Comment by ayesha1093** [comment]
Hi,
Can you share the code if you were able to figure it out?
