### ISSUE TITLE
what is difference between n_instance and n_features?

### ISSUE THREAD

**Issue by Haebuk** [yuezhihan/ts2vec#13]
in ts2vec.py, `fit()` requires `train_data` type (n_instance. n_timestamps, n_features).
what is difference between n_instance and n_features?
I think n_feature means the number of time series (e.g. univariate time series -> n_features=1)
Is same that n_instance to window size? or something?
thank you.

**Comment by yuezhihan** [comment]
"instance" means "sample". The difference between instances and features is that instances generally come from the same distribution. For example, for stock market, `n_instance` is the number of stocks, and `n_features` is the number of features (e.g. open, high, low, close, volume). For traffic flow, `n_instance` can be the number of roads, and `n_features` is the number of features collected on the road.
