### ISSUE TITLE
请问关于encoder中的相关问题

### ISSUE THREAD

**Issue by guobing21** [yuezhihan/ts2vec#23]
![微信图片_20220825151336](https://user-images.githubusercontent.com/53030217/186600038-0cc5401e-f71d-43c7-ad50-04d7232db8c5.jpg)
大佬您好，想请问下encoder中的Dilated Convolutions。
1. 我看代码后的理解是，分别将a1-b1子序列和a2-b2子序列送入encoder，得到两个子序列表征。再对两个子序列时间公共的部分a2~b1进行对比学习。可以这么理解吗？
2. 请问encoder中的Dilated Convolution是因果卷积吗？是每一点的表征学习只用到了该时刻及之前的数据？
3. 如果是因果卷积，可否认为将a2-b2子序列送入encoder学习表征时，a2-b1段学到的表征，没有使用到b1-b2段的信息？

恳请大佬答疑解惑，多谢多谢！

**Comment by yuezhihan** [comment]
1、可以。
2、不是因果卷积，每一点的表征都包含了前后的信息。

**Comment by guobing21** [comment]
您好，我想再请问下：
    如果不是因果卷积，那把测试集的数据输入到encoder，去得到表征的时候，每个点的表征也用到了这个点后面的信息了？那这样岂不是有标签泄露吗？

**Comment by yuezhihan** [comment]
> 您好，我想再请问下： 1 如果不是因果卷积，那再做预测任务时，那把测试集的数据输入到decode，得到表征的时候，每个点的表征也用到了这个点后面的信息了？那这样岂不是有标签泄露吗？ 2 我看了您写的Dilated Convolution这部分代码，这部分代码应该是TCN代码吧，TCN不是包含了因果卷积和膨胀卷积吗?
> 
> 恳请大佬答疑解惑，多谢多谢！
> 
> ```python
> class DilatedConvEncoder(nn.Module):
>     def __init__(self, in_channels, channels, kernel_size):
>         super().__init__()
>         self.net = nn.Sequential(*[
>             ConvBlock(
>                 channels[i-1] if i > 0 else in_channels,
>                 channels[i],
>                 kernel_size=kernel_size,
>                 dilation=2**i,
>                 final=(i == len(channels)-1)
>             )
>             for i in range(len(channels))
>         ])
>         
>     def forward(self, x):
>         return self.net(x)
> 
> class ConvBlock(nn.Module):
>     def __init__(self, in_channels, out_channels, kernel_size, dilation, final=False):
>         super().__init__()
>         self.conv1 = SamePadConv(in_channels, out_channels, kernel_size, dilation=dilation)
>         self.conv2 = SamePadConv(out_channels, out_channels, kernel_size, dilation=dilation)
>         self.projector = nn.Conv1d(in_channels, out_channels, 1) if in_channels != out_channels or final else None
>     
>     def forward(self, x):
>         residual = x if self.projector is None else self.projector(x)
>         x = F.gelu(x)
>         x = self.conv1(x)
>         x = F.gelu(x)
>         x = self.conv2(x)
>         return x + residual
> 
> class SamePadConv(nn.Module):
>     def __init__(self, in_channels, out_channels, kernel_size, dilation=1, groups=1):
>         super().__init__()
>         self.receptive_field = (kernel_size - 1) * dilation + 1
>         padding = self.receptive_field // 2
>         self.conv = nn.Conv1d(
>             in_channels, out_channels, kernel_size,
>             padding=padding,
>             dilation=dilation,
>             groups=groups
>         )
>         self.remove = 1 if self.receptive_field % 2 == 0 else 0
>         
>     def forward(self, x):
>         out = self.conv(x)
>         if self.remove > 0:
>             out = out[:, :, : -self.remove]
>         return out
> ```

1、不需要因果卷积，inference时不输入未来数据，或把未来数据mask掉即可。见 #7。

2、只用了膨胀卷积。跟TCN略有区别，具体可以对比我们的代码和TCN的代码。

**Comment by guobing21** [comment]
“1、不需要因果卷积，inference时不输入未来数据，或把未来数据mask掉即可。“，麻烦再请问下，在进行电力数据预测实验时，我看是将测试集数据都送入到model.encode中去了。这个是把未来数据mask掉了吗？

恳请大佬答疑解惑

**Comment by yuezhihan** [comment]
> “1、不需要因果卷积，inference时不输入未来数据，或把未来数据mask掉即可。“，麻烦再请问下，在进行电力数据预测实验时，我看是将测试集数据都送入到model.encode中去了。这个是把未来数据mask掉了吗？
> 
> 恳请大佬答疑解惑。
> 
> ```python
> all_repr = model.encode(
>     data,
>     casual=True,
>     sliding_length=1,
>     sliding_padding=padding,
>     batch_size=256
> )
> ```

这里的casual=True，就是指定了不输入未来数据。相当于每个时间点t都构建一个样本，这个样本包含t和t之前的数据做输入。

**Comment by yuezhihan** [comment]
不直接用casual conv的原因是，并不是任何时序任务都不用t之后的数据，casual conv限制了模型的应用范围，比如可以设想这样一个补全任务“部分时刻数据缺失，如果t时刻缺失可以用t周围的补全”，这个任务就可以mask掉t这个点，然后用周围的补全。所以在需要casual的时候，用casual inference（即滚动向前预测，不输入之后的数据），不需要的时候不用，不用更改模型设计就能用于各种任务，其实是一种更灵活的设计。

**Comment by guobing21** [comment]
> 



> > 您好，我想再请问下： 1 如果不是因果卷积，那再做预测任务时，那把测试集的数据输入到decode，得到表征的时候，每个点的表征也用到了这个点后面的信息了？那这样岂不是有标签泄露吗？ 2 我看了您写的Dilated Convolution这部分代码，这部分代码应该是TCN代码吧，TCN不是包含了因果卷积和膨胀卷积吗?
> > 恳请大佬答疑解惑，多谢多谢！
> > ```python
> > class DilatedConvEncoder(nn.Module):
> >     def __init__(self, in_channels, channels, kernel_size):
> >         super().__init__()
> >         self.net = nn.Sequential(*[
> >             ConvBlock(
> >                 channels[i-1] if i > 0 else in_channels,
> >                 channels[i],
> >                 kernel_size=kernel_size,
> >                 dilation=2**i,
> >                 final=(i == len(channels)-1)
> >             )
> >             for i in range(len(channels))
> >         ])
> >         
> >     def forward(self, x):
> >         return self.net(x)
> > 
> > class ConvBlock(nn.Module):
> >     def __init__(self, in_channels, out_channels, kernel_size, dilation, final=False):
> >         super().__init__()
> >         self.conv1 = SamePadConv(in_channels, out_channels, kernel_size, dilation=dilation)
> >         self.conv2 = SamePadConv(out_channels, out_channels, kernel_size, dilation=dilation)
> >         self.projector = nn.Conv1d(in_channels, out_channels, 1) if in_channels != out_channels or final else None
> >     
> >     def forward(self, x):
> >         residual = x if self.projector is None else self.projector(x)
> >         x = F.gelu(x)
> >         x = self.conv1(x)
> >         x = F.gelu(x)
> >         x = self.conv2(x)
> >         return x + residual
> > 
> > class SamePadConv(nn.Module):
> >     def __init__(self, in_channels, out_channels, kernel_size, dilation=1, groups=1):
> >         super().__init__()
> >         self.receptive_field = (kernel_size - 1) * dilation + 1
> >         padding = self.receptive_field // 2
> >         self.conv = nn.Conv1d(
> >             in_channels, out_channels, kernel_size,
> >             padding=padding,
> >             dilation=dilation,
> >             groups=groups
> >         )
> >         self.remove = 1 if self.receptive_field % 2 == 0 else 0
> >         
> >     def forward(self, x):
> >         out = self.conv(x)
> >         if self.remove > 0:
> >             out = out[:, :, : -self.remove]
> >         return out
> > ```
> 
> 1、不需要因果卷积，inference时不输入未来数据，或把未来数据mask掉即可。见 #7。
> 
> 2、只用了膨胀卷积。跟TCN略有区别，具体可以对比我们的代码和TCN的代码。

非常感谢大佬的回答。请问下代码主要是哪里改动，导致没有了因果卷积部分，只剩下了膨胀卷积部分。恳求大佬解惑

**Comment by yuezhihan** [comment]
> > > 您好，我想再请问下： 1 如果不是因果卷积，那再做预测任务时，那把测试集的数据输入到decode，得到表征的时候，每个点的表征也用到了这个点后面的信息了？那这样岂不是有标签泄露吗？ 2 我看了您写的Dilated Convolution这部分代码，这部分代码应该是TCN代码吧，TCN不是包含了因果卷积和膨胀卷积吗?
> > > 恳请大佬答疑解惑，多谢多谢！
> > > ```python
> > > class DilatedConvEncoder(nn.Module):
> > >     def __init__(self, in_channels, channels, kernel_size):
> > >         super().__init__()
> > >         self.net = nn.Sequential(*[
> > >             ConvBlock(
> > >                 channels[i-1] if i > 0 else in_channels,
> > >                 channels[i],
> > >                 kernel_size=kernel_size,
> > >                 dilation=2**i,
> > >                 final=(i == len(channels)-1)
> > >             )
> > >             for i in range(len(channels))
> > >         ])
> > >         
> > >     def forward(self, x):
> > >         return self.net(x)
> > > 
> > > class ConvBlock(nn.Module):
> > >     def __init__(self, in_channels, out_channels, kernel_size, dilation, final=False):
> > >         super().__init__()
> > >         self.conv1 = SamePadConv(in_channels, out_channels, kernel_size, dilation=dilation)
> > >         self.conv2 = SamePadConv(out_channels, out_channels, kernel_size, dilation=dilation)
> > >         self.projector = nn.Conv1d(in_channels, out_channels, 1) if in_channels != out_channels or final else None
> > >     
> > >     def forward(self, x):
> > >         residual = x if self.projector is None else self.projector(x)
> > >         x = F.gelu(x)
> > >         x = self.conv1(x)
> > >         x = F.gelu(x)
> > >         x = self.conv2(x)
> > >         return x + residual
> > > 
> > > class SamePadConv(nn.Module):
> > >     def __init__(self, in_channels, out_channels, kernel_size, dilation=1, groups=1):
> > >         super().__init__()
> > >         self.receptive_field = (kernel_size - 1) * dilation + 1
> > >         padding = self.receptive_field // 2
> > >         self.conv = nn.Conv1d(
> > >             in_channels, out_channels, kernel_size,
> > >             padding=padding,
> > >             dilation=dilation,
> > >             groups=groups
> > >         )
> > >         self.remove = 1 if self.receptive_field % 2 == 0 else 0
> > >         
> > >     def forward(self, x):
> > >         out = self.conv(x)
> > >         if self.remove > 0:
> > >             out = out[:, :, : -self.remove]
> > >         return out
> > > ```
> > 
> > 
> > 1、不需要因果卷积，inference时不输入未来数据，或把未来数据mask掉即可。见 #7。
> > 2、只用了膨胀卷积。跟TCN略有区别，具体可以对比我们的代码和TCN的代码。
> 
> 非常感谢大佬的回答。请问下代码主要是哪里改动，导致没有了因果卷积部分，只剩下了膨胀卷积部分。恳求大佬解惑

膨胀卷积的代码不是从TCN改的，哪些细节不一样你需要自己看一下。因果卷积不是一个网络模块，正常卷积shift半个kernel size就是因果卷积，实现上左边多一点padding，就相当于shift了。

**Comment by guobing21** [comment]
> > > > 您好，我想再请问下： 1 如果不是因果卷积，那再做预测任务时，那把测试集的数据输入到decode，得到表征的时候，每个点的表征也用到了这个点后面的信息了？那这样岂不是有标签泄露吗？ 2 我看了您写的Dilated Convolution这部分代码，这部分代码应该是TCN代码吧，TCN不是包含了因果卷积和膨胀卷积吗?
> > > > 恳请大佬答疑解惑，多谢多谢！
> > > > ```python
> > > > class DilatedConvEncoder(nn.Module):
> > > >     def __init__(self, in_channels, channels, kernel_size):
> > > >         super().__init__()
> > > >         self.net = nn.Sequential(*[
> > > >             ConvBlock(
> > > >                 channels[i-1] if i > 0 else in_channels,
> > > >                 channels[i],
> > > >                 kernel_size=kernel_size,
> > > >                 dilation=2**i,
> > > >                 final=(i == len(channels)-1)
> > > >             )
> > > >             for i in range(len(channels))
> > > >         ])
> > > >         
> > > >     def forward(self, x):
> > > >         return self.net(x)
> > > > 
> > > > class ConvBlock(nn.Module):
> > > >     def __init__(self, in_channels, out_channels, kernel_size, dilation, final=False):
> > > >         super().__init__()
> > > >         self.conv1 = SamePadConv(in_channels, out_channels, kernel_size, dilation=dilation)
> > > >         self.conv2 = SamePadConv(out_channels, out_channels, kernel_size, dilation=dilation)
> > > >         self.projector = nn.Conv1d(in_channels, out_channels, 1) if in_channels != out_channels or final else None
> > > >     
> > > >     def forward(self, x):
> > > >         residual = x if self.projector is None else self.projector(x)
> > > >         x = F.gelu(x)
> > > >         x = self.conv1(x)
> > > >         x = F.gelu(x)
> > > >         x = self.conv2(x)
> > > >         return x + residual
> > > > 
> > > > class SamePadConv(nn.Module):
> > > >     def __init__(self, in_channels, out_channels, kernel_size, dilation=1, groups=1):
> > > >         super().__init__()
> > > >         self.receptive_field = (kernel_size - 1) * dilation + 1
> > > >         padding = self.receptive_field // 2
> > > >         self.conv = nn.Conv1d(
> > > >             in_channels, out_channels, kernel_size,
> > > >             padding=padding,
> > > >             dilation=dilation,
> > > >             groups=groups
> > > >         )
> > > >         self.remove = 1 if self.receptive_field % 2 == 0 else 0
> > > >         
> > > >     def forward(self, x):
> > > >         out = self.conv(x)
> > > >         if self.remove > 0:
> > > >             out = out[:, :, : -self.remove]
> > > >         return out
> > > > ```
> > > 
> > > 
> > > 1、不需要因果卷积，inference时不输入未来数据，或把未来数据mask掉即可。见 #7。
> > > 2、只用了膨胀卷积。跟TCN略有区别，具体可以对比我们的代码和TCN的代码。
> > 
> > 
> > 非常感谢大佬的回答。请问下代码主要是哪里改动，导致没有了因果卷积部分，只剩下了膨胀卷积部分。恳求大佬解惑
> 
> 膨胀卷积的代码不是从TCN改的，哪些细节不一样你需要自己看一下。因果卷积不是一个网络模块，正常卷积shift半个感受野就是因果卷积，实现上因果多了半个感受野的padding，就相当于shift了。

多谢大佬解答。具体实现上，可否认为是：
1 TCN的padding为(kernel_size - 1) * dilation，而ts2vec的膨胀卷积padding为（(kernel_size - 1) * dilation）//2。
2 TCN为了保证输入输出等长，丢弃了数据右边padding 0 后卷积生成的结果。而ts2vec的膨胀卷积对这部分进行了保留，相应的padding大小就要减半。最后再将卷积结果依次排列。因此第t个点的卷积结果，实际上使用了t点之后的信息？
恳请大佬答疑解惑，多谢多谢！

**Comment by guobing21** [comment]
> > > > > 您好，我想再请问下： 1 如果不是因果卷积，那再做预测任务时，那把测试集的数据输入到decode，得到表征的时候，每个点的表征也用到了这个点后面的信息了？那这样岂不是有标签泄露吗？ 2 我看了您写的Dilated Convolution这部分代码，这部分代码应该是TCN代码吧，TCN不是包含了因果卷积和膨胀卷积吗?
> > > > > 恳请大佬答疑解惑，多谢多谢！
> > > > > ```python
> > > > > class DilatedConvEncoder(nn.Module):
> > > > >     def __init__(self, in_channels, channels, kernel_size):
> > > > >         super().__init__()
> > > > >         self.net = nn.Sequential(*[
> > > > >             ConvBlock(
> > > > >                 channels[i-1] if i > 0 else in_channels,
> > > > >                 channels[i],
> > > > >                 kernel_size=kernel_size,
> > > > >                 dilation=2**i,
> > > > >                 final=(i == len(channels)-1)
> > > > >             )
> > > > >             for i in range(len(channels))
> > > > >         ])
> > > > >         
> > > > >     def forward(self, x):
> > > > >         return self.net(x)
> > > > > 
> > > > > class ConvBlock(nn.Module):
> > > > >     def __init__(self, in_channels, out_channels, kernel_size, dilation, final=False):
> > > > >         super().__init__()
> > > > >         self.conv1 = SamePadConv(in_channels, out_channels, kernel_size, dilation=dilation)
> > > > >         self.conv2 = SamePadConv(out_channels, out_channels, kernel_size, dilation=dilation)
> > > > >         self.projector = nn.Conv1d(in_channels, out_channels, 1) if in_channels != out_channels or final else None
> > > > >     
> > > > >     def forward(self, x):
> > > > >         residual = x if self.projector is None else self.projector(x)
> > > > >         x = F.gelu(x)
> > > > >         x = self.conv1(x)
> > > > >         x = F.gelu(x)
> > > > >         x = self.conv2(x)
> > > > >         return x + residual
> > > > > 
> > > > > class SamePadConv(nn.Module):
> > > > >     def __init__(self, in_channels, out_channels, kernel_size, dilation=1, groups=1):
> > > > >         super().__init__()
> > > > >         self.receptive_field = (kernel_size - 1) * dilation + 1
> > > > >         padding = self.receptive_field // 2
> > > > >         self.conv = nn.Conv1d(
> > > > >             in_channels, out_channels, kernel_size,
> > > > >             padding=padding,
> > > > >             dilation=dilation,
> > > > >             groups=groups
> > > > >         )
> > > > >         self.remove = 1 if self.receptive_field % 2 == 0 else 0
> > > > >         
> > > > >     def forward(self, x):
> > > > >         out = self.conv(x)
> > > > >         if self.remove > 0:
> > > > >             out = out[:, :, : -self.remove]
> > > > >         return out
> > > > > ```
> > > > 
> > > > 
> > > > 1、不需要因果卷积，inference时不输入未来数据，或把未来数据mask掉即可。见 #7。
> > > > 2、只用了膨胀卷积。跟TCN略有区别，具体可以对比我们的代码和TCN的代码。
> > > 
> > > 
> > > 非常感谢大佬的回答。请问下代码主要是哪里改动，导致没有了因果卷积部分，只剩下了膨胀卷积部分。恳求大佬解惑
> > 
> > 
> > 膨胀卷积的代码不是从TCN改的，哪些细节不一样你需要自己看一下。因果卷积不是一个网络模块，正常卷积shift半个感受野就是因果卷积，实现上因果多了半个感受野的padding，就相当于shift了。
> 
> 多谢大佬解答。具体实现上，可否认为是： 1 TCN的padding为(kernel_size - 1) * dilation，而ts2vec的膨胀卷积padding为（(kernel_size - 1) * dilation）//2。 2 TCN为了保证输入输出等长，丢弃了数据右边padding 0 后卷积生成的结果。而ts2vec的膨胀卷积对这部分进行了保留，相应的padding大小就要减半。最后再将卷积结果依次往前顺位。因此第t个点的卷积结果，实际上使用了t点之后的信息？ 恳请大佬答疑解惑，多谢多谢！

**Comment by yuezhihan** [comment]
> > > > > > 您好，我想再请问下： 1 如果不是因果卷积，那再做预测任务时，那把测试集的数据输入到decode，得到表征的时候，每个点的表征也用到了这个点后面的信息了？那这样岂不是有标签泄露吗？ 2 我看了您写的Dilated Convolution这部分代码，这部分代码应该是TCN代码吧，TCN不是包含了因果卷积和膨胀卷积吗?
> > > > > > 恳请大佬答疑解惑，多谢多谢！
> > > > > > ```python
> > > > > > class DilatedConvEncoder(nn.Module):
> > > > > >     def __init__(self, in_channels, channels, kernel_size):
> > > > > >         super().__init__()
> > > > > >         self.net = nn.Sequential(*[
> > > > > >             ConvBlock(
> > > > > >                 channels[i-1] if i > 0 else in_channels,
> > > > > >                 channels[i],
> > > > > >                 kernel_size=kernel_size,
> > > > > >                 dilation=2**i,
> > > > > >                 final=(i == len(channels)-1)
> > > > > >             )
> > > > > >             for i in range(len(channels))
> > > > > >         ])
> > > > > >         
> > > > > >     def forward(self, x):
> > > > > >         return self.net(x)
> > > > > > 
> > > > > > class ConvBlock(nn.Module):
> > > > > >     def __init__(self, in_channels, out_channels, kernel_size, dilation, final=False):
> > > > > >         super().__init__()
> > > > > >         self.conv1 = SamePadConv(in_channels, out_channels, kernel_size, dilation=dilation)
> > > > > >         self.conv2 = SamePadConv(out_channels, out_channels, kernel_size, dilation=dilation)
> > > > > >         self.projector = nn.Conv1d(in_channels, out_channels, 1) if in_channels != out_channels or final else None
> > > > > >     
> > > > > >     def forward(self, x):
> > > > > >         residual = x if self.projector is None else self.projector(x)
> > > > > >         x = F.gelu(x)
> > > > > >         x = self.conv1(x)
> > > > > >         x = F.gelu(x)
> > > > > >         x = self.conv2(x)
> > > > > >         return x + residual
> > > > > > 
> > > > > > class SamePadConv(nn.Module):
> > > > > >     def __init__(self, in_channels, out_channels, kernel_size, dilation=1, groups=1):
> > > > > >         super().__init__()
> > > > > >         self.receptive_field = (kernel_size - 1) * dilation + 1
> > > > > >         padding = self.receptive_field // 2
> > > > > >         self.conv = nn.Conv1d(
> > > > > >             in_channels, out_channels, kernel_size,
> > > > > >             padding=padding,
> > > > > >             dilation=dilation,
> > > > > >             groups=groups
> > > > > >         )
> > > > > >         self.remove = 1 if self.receptive_field % 2 == 0 else 0
> > > > > >         
> > > > > >     def forward(self, x):
> > > > > >         out = self.conv(x)
> > > > > >         if self.remove > 0:
> > > > > >             out = out[:, :, : -self.remove]
> > > > > >         return out
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 1、不需要因果卷积，inference时不输入未来数据，或把未来数据mask掉即可。见 #7。
> > > > > 2、只用了膨胀卷积。跟TCN略有区别，具体可以对比我们的代码和TCN的代码。
> > > > 
> > > > 
> > > > 非常感谢大佬的回答。请问下代码主要是哪里改动，导致没有了因果卷积部分，只剩下了膨胀卷积部分。恳求大佬解惑
> > > 
> > > 
> > > 膨胀卷积的代码不是从TCN改的，哪些细节不一样你需要自己看一下。因果卷积不是一个网络模块，正常卷积shift半个感受野就是因果卷积，实现上因果多了半个感受野的padding，就相当于shift了。
> > 
> > 
> > 多谢大佬解答。具体实现上，可否认为是：
> 
> 1. TCN的padding为(kernel_size - 1) * dilation，而ts2vec的膨胀卷积padding为（(kernel_size - 1) * dilation）//2。
> 2. 为了保证输入输出等长，TCN的做法是丢弃了对时序数据右边padding 0 卷积生成的结果。而ts2vec的膨胀卷积对这部分卷积结果进行了保留，相应的padding大小就要减半。最后再将卷积结果依次往前顺位。因此第t个点的卷积结果，实际上使用了t点之后的信息？
>    恳请大佬答疑解惑，多谢多谢！

是的
