### ISSUE TITLE
Pre-processing for Electricity dataset

### ISSUE THREAD

**Issue by gorold** [yuezhihan/ts2vec#3]
Hi, congratulations on the impressive results. May I check if you are able to give more details about the pre-processing details for the electricity dataset, or provide the pre-processing code? Do you use simple resampling, or do you take the average of each hour? Thank you!

**Comment by yuezhihan** [comment]
We resample the data into the total consumption (sum) of each hour. The data can be preprocessed like this:
```python
import pandas as pd
data_ecl = pd.read_csv('LD2011_2014.txt', parse_dates=True, sep=';', decimal=',', index_col=0)
data_ecl = data_ecl.resample('1h', closed='right').sum()
data_ecl = data_ecl.loc[:, data_ecl.cumsum(axis=0).iloc[8920] != 0]  # filter out instances with missing values
data_ecl.index = data_ecl.index.rename('date')
data_ecl = data_ecl['2012':]
```
