### ISSUE TITLE
ETTh1 data dimension mismatch problem

### ISSUE THREAD

**Issue by zifei-yu** [yuezhihan/ts2vec#30]
Hello, I have also been studying the ts2vec model recently. When I used the ETTh1 dataset, I encountered a dimension inconsistency problem. Have you ever encountered this problem? I hope to receive your answer. Thank you very much!

**Comment by yuezhihan** [comment]
This may be due to an inconsistent version of sklearn. Are you using sklearn 0.24.2?

**Comment by zifei-yu** [comment]
> 这可能是由于 sklearn 的版本不一致。你在使用 sklearn 0.24.2 吗？

Thank you very much for your answer. The problem has been resolved. Thank you again for your kind response during your busy schedule. Thank you!
