### ISSUE TITLE
where can I download 'electricity.csv'

### ISSUE THREAD

**Issue by hehaodele** [yuezhihan/ts2vec#4]
Hi Zhihan,

Thanks for the very useful repository. Could you point me to the place where I can download the 'electricity.csv'. From the link in the README, [Electricity dataset ](https://archive.ics.uci.edu/ml/datasets/ElectricityLoadDiagrams20112014), I can only get a file named LD2011_2014.txt.zip. Not sure how to convert it to the 'electricity.csv'.

**Comment by yuezhihan** [comment]
We resample the data into the total consumption (sum) of each hour. The data can be preprocessed like this:

```py
import pandas as pd
data_ecl = pd.read_csv('LD2011_2014.txt', parse_dates=True, sep=';', decimal=',', index_col=0)
data_ecl = data_ecl.resample('1h', closed='right').sum()
data_ecl = data_ecl.loc[:, data_ecl.cumsum(axis=0).iloc[8920] != 0]  # filter out instances with missing values
data_ecl.index = data_ecl.index.rename('date')
data_ecl = data_ecl['2012':]
data_ecl.to_csv('electricity.csv')
```

**Comment by hehaodele** [comment]
awesome! thank you.
