### ISSUE TITLE
Format of Yahoo dataset for pre-processing

### ISSUE THREAD

**Issue by gorold** [yuezhihan/ts2vec#6]
Thank you so much for continuously open-sourcing your findings! I noticed that the downloaded data from Yahoo seems to be in a different format than the one required for preprocess_yahoo.py. Will it be possible for you to look into this? Thank you very much!

Yahoo follows the format of 
A1/real_1.csv
...
A2/synthetic_1.csv
...

While the required format is path/1 ... path/367, which seems to contain dictionaries.

**Comment by yuezhihan** [comment]
Hi, thank you for your feedback. We have fixed this.
